### ISSUE TITLE
Not able to set temperature

### ISSUE THREAD

**Issue by jahnkenneth** [jghaanstra/com.yeelight#10]
After the last update I am not able to set temperature on my Yeelight Lightstrip plus. 
when setting a temperature via a flow I get “device is not defined”.

**Comment by jghaanstra** [comment]
Could you trigger the flow and send me a diagnostic report from the app settings afterwards.

**Comment by jahnkenneth** [comment]
Sent. 
ID: 849f4e02-8716-4afa-b1ea-873fe1a201b2

**Comment by jghaanstra** [comment]
Not much info in the log, have you tried restarting the app?

**Comment by jahnkenneth** [comment]
Yes, have tried restarting the app. Does not solve the problem.

**Comment by jghaanstra** [comment]
Could you tell me the model id which can be found in the Yeelight app.

**Comment by jahnkenneth** [comment]
Yeelink.light.strip6

**Comment by jghaanstra** [comment]
I checked the changes in my app of the last two months but I have not touched the code for setting temperature of the LED strip. So this either has been broken for quite some time already, it never worked or it's not working for you perhaps because of a recent firmware of the LED strip.

What kelvin range does the strip support?

**Comment by jahnkenneth** [comment]
Hello,
It was working until yesterday. 
I do not know if it has been automatically updated. 

Med hilsen,
Jahn Kenneth Juliussen

**Comment by jahnkenneth** [comment]
![Uploading 16AD268E-E9AF-4DEF-A989-121078143B23.png…]()

**Comment by jahnkenneth** [comment]
![01ED5374-AEE1-42E1-AC3D-CFF32B48B88C](https://user-images.githubusercontent.com/28279147/116395216-218b5300-a824-11eb-90e2-7d1541581c56.jpeg)

**Comment by jahnkenneth** [comment]
![E84AFBC8-7003-4279-87CB-D59F5395967A](https://user-images.githubusercontent.com/28279147/116395267-32d45f80-a824-11eb-9fc9-fb1161a3cc01.png)

**Comment by jahnkenneth** [comment]
I have also tried restarting Homey.

**Comment by jghaanstra** [comment]
I dont know what it is. 

> What kelvin range does the strip support?
> 
> And re-pairing might help as well.

**Comment by jahnkenneth** [comment]
Kelvin range 2700 - 6500K. 
have tried re pairing…

**Comment by jghaanstra** [comment]
Well, I'm clueless. You can try installing a previous release using the command line to see if that helps.

**Comment by jghaanstra** [comment]
I'll also revert a change in the last release that might be related to this. But cant promise it will fix this.

**Comment by jahnkenneth** [comment]
> Well, I'm clueless. You can try installing a previous release using the command line to see if that helps.

I know how to use cli, but how do I find the previous version? :-)

**Comment by jghaanstra** [comment]
https://github.com/jghaanstra/com.yeelight/releases/tag/3.0.5

**Comment by jahnkenneth** [comment]
Installed 3.0.5, and now it’s working again. :-)

**Comment by jghaanstra** [comment]
Could you check if release 3.0.8 (now available in the app store) fixes this issue.

**Comment by jahnkenneth** [comment]
It does. :-)
