### ISSUE TITLE
Hue flow problem

### ISSUE THREAD

**Issue by damianxd** [jghaanstra/com.yeelight#12]
I’m having troubles with the hue flow, whatever value I choose while using the scroll bar from 0 to 360, the lamp will just show a kind of bluish light. I’m using the bulb 1s (color)

**Comment by jghaanstra** [comment]
This is the repository of the Yeelight app, not the hue app.

**Comment by damianxd** [comment]
I think you misunderstood the problem, it’s not the hue app what I’m talking about, it’s the hue flow the yeelight app has.

**Comment by jghaanstra** [comment]
Fixed with release 3.0.10.

**Comment by damianxd** [comment]
thank you so much for the quick fix and thank you for your awesome work!
