### ISSUE TITLE
Yeelight dimt niet.

### ISSUE THREAD

**Issue by Sagazine** [jghaanstra/com.yeelight#13]
Bis een flow dimt de Yeelight YLDP12YL niet. Hij schakelt alleen aan en uit. Via apparaten kan ik de lamp wel dimmen.

**Comment by jghaanstra** [comment]
Could you post the model identifier as shown under the device settings in the official Yeelight app.

**Comment by Sagazine** [comment]
You mean the attachment?


Mark

Op za 8 jan. 2022 21:38 schreef Jelger Haanstra ***@***.***>:

**Comment by jghaanstra** [comment]
What attachment? As mentioned, you need to supply me the model id which can be found in the settings the official Yeelight app.
