### ISSUE TITLE
Yeelight

### ISSUE THREAD

**Issue by TazzieRL** [jghaanstra/com.yeelight#14]
Hi There,

since a week or 3, i cannot control the yeelight by homey.

Nothing is changed, i allready reinstall de app / ledstrip in homey.
What i saw is when i remotly set the strip on i see in de homey status to on, en vice  versa.
i cannot switch it on of off by homey

help :)

gr Rini

**Comment by jghaanstra** [comment]
Please use the support topic on the community forum for support. Github is for bugs and feature requests.
