### ISSUE TITLE
All Yeelight disconnected

### ISSUE THREAD

**Issue by adrienbernard** [jghaanstra/com.yeelight#15]
Hello,
All Yeelight lamps are disconnected and nothing has been touched in Homey.
No update of the app has been done and no update of the Homey has been done.
Reboot of the app and Homey has been done but still not able to connect to devices.
Homey report: 6f3a7646-b535-4aac-82e0-7ee6972cf3b5
For information, I'm still able to control devices from Yeelight app.
What else can be done ?
Best regards.

**Comment by jghaanstra** [comment]
As mentioned in respond to your crash log. It's your own network of the network stability of Homey. Not something I can fix for you.
