### ISSUE TITLE
Dim to command Duration parameter is ignored

### ISSUE THREAD

**Issue by Moskvitch** [jghaanstra/com.yeelight#2]
Dim straight to the set level ignoring the duration parameter not allowing gradual fadein/fadeout.

**Comment by jghaanstra** [comment]
I probably fixed it. Do you have the technical skills to install the app from the command line to confirm the issue has been resolved?

https://github.com/jghaanstra/com.yeelight

**Comment by jghaanstra** [comment]
Closed due to inactivity. Will probably be fixed with a new release.
