### ISSUE TITLE
Na het resetten van de lamp, kan ik geen nieuwe lampen vinden in de homey app, wel toegevoegd in de yeelight app. Wat doe ik verkeerd? Heb je een tip?

### ISSUE THREAD

**Issue by Nico82p** [jghaanstra/com.yeelight#20]

**Comment by jghaanstra** [comment]
Stop using Github for this support and use the support forum instead. You probably need to enable LAN control as mentioned in the pairing instructions.

https://community.homey.app/t/app-yeelights-lan-needs-other-developer/21134
