### ISSUE TITLE
Yeelight Screen bar pro

### ISSUE THREAD

**Issue by Youpvdberg** [jghaanstra/com.yeelight#21]
I am using the Yeelight screen light bar pro which has a front CCT screenbar and an RGB backlight. The CCT light is controlable via Homey however the RGB backlight does not pop up as separate device. Via the Xiaomi home and the Yeelight app the RGB backlight is controllable. Maybe there is an separate http command or API command which you could use for the RGB backlighting. 

Using Yeelight Homey App version : 3.0.17
Homey pro 2019 : version 10.0.2

**Comment by jghaanstra** [comment]
I'm not really supporting this app anymore but I'll see if there is a quick fix. What is the device model id and model number? You should be able to find it in the app. The model ID will be a name, something like `desklamp` and the model ID will be something like `YLTD002`.

**Comment by Youpvdberg** [comment]
Thank you for the quick reply! 
The model number is  : YLTD003 
The app does not seem to give specific information about the model ID

The standard name of the product in the app is ''Yeelight screen light bar''

I found this integration but i don't know if these id's are specific to Home Assistant or identical from Yeelight 
https://www.home-assistant.io/integrations/yeelight/

Where should i be able to find the model ID name?

**Comment by jghaanstra** [comment]
Based on the model number I have found the model ID. I'll add it when I have more time.

**Comment by jghaanstra** [comment]
Added with release 3.0.18.

**Comment by Youpvdberg** [comment]
Wow many thanks! it works now 👍
