### ISSUE TITLE
Custom command samples

### ISSUE THREAD

**Issue by W-illi4m** [jghaanstra/com.yeelight#22]
Hi, 
I would like to call a custom colour scene in a flow. 
Do you have some samples ?
Regards, 
William

**Comment by W-illi4m** [comment]
I tried that command line without success :

{"id":1,"method":"start_cf","params":[ 4, 2, "1000, 2, 2700, 100, 500, 1, 
255, 10, 5000, 7, 0,0, 500, 2, 5000, 1"]}

**Comment by jghaanstra** [comment]
Everything you need to know is in the documentation.

https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf
