### ISSUE TITLE
EU server

### ISSUE THREAD

**Issue by irven71** [jghaanstra/com.yeelight#23]
I have all my devices installed on EU server, my Yeelight app sees it correctly.
But when I try to use this app, I have to choose China server to see correctly my devices, and this causes a lot of LAG. Any other control system (home assistant, Yeelight App, Xiaomi app) uses EU server and works immediatly, with no delay

**Comment by irven71** [comment]
My bad, I used wrong app, now it works. But I still do not see some products, like Bed Lamp 2, also if LAN control is enabled and it works via other app (Home Assistant). Is there any way to control everything?

**Comment by jghaanstra** [comment]
Other users are using the Bedside Lamp 2 with this app already. Must be a user error.

https://community.homey.app/t/app-yeelights-lan-needs-other-developer/21134/68
