### ISSUE TITLE
Ceiling Light 650 ambilight

### ISSUE THREAD

**Issue by strejcd** [jghaanstra/com.yeelight#4]
Hi Jelger, would it be possible to add On/Off/Toggle + Brightness functionality for the Ceiling Light 650 ambilight? (ceiling4 I guess). There is no way how to operate the color led stripe on this lamp. Also along with the appropriate Flows to trigger. Many thanks apprecite an effort.

Similar what Maxmudjon has in his app [https://github.com/easyhomesrc/Homey_Issues](url)
![light](https://user-images.githubusercontent.com/60077600/72997149-2fba1a80-3dfc-11ea-83ca-19f469d66a76.PNG)

**Comment by jghaanstra** [comment]
Yeah, that is possible but requires quite a lot of refactoring. I dont have much time ATM to work on this so I'll look into it at a later time.

**Comment by jghaanstra** [comment]
Added with release 1.1.0 which is pending app store approval.

https://github.com/jghaanstra/com.yeelight/releases/tag/1.1.0
