### ISSUE TITLE
set random colour

### ISSUE THREAD

**Issue by glennhmjoat** [jghaanstra/com.yeelight#5]
I have a bulb that is set to come on at sunset to a random colour
It will work fine 5 or 6 times then just gets stuck on white when set random colour in a flow is triggered.
I can set a colour manually fine, or specify a single colour in a flow.

The flow is just 
-at sunset then... 
-turn light on
-set random colour

Setting a relative dim broke the flow as well.
The bulb is one of these, 
Xiaomi Yeelight Smart LED Bulb E27 10W 800 Lumens WIFI Bulb
Diagnostics number
b7b51bf6-871c-49fa-b507-2bad27e17f5c

**Comment by jghaanstra** [comment]
The random color card is built in card from Athom and I have no control over it. But I use it myself and I do not see this behaviour. I do power of my light every day with a physical switch though. Perhaps it's something with the Yeelight firmware. Either way, there is not much I can do about it.

I did not a lot of unreachable lights in the log that you send me. This is fine if these lights are powered of. If they are not you should look into the WiFi connectivity of your lights.
