### ISSUE TITLE
Different icons for devices

### ISSUE THREAD

**Issue by ElvisPresly** [jghaanstra/com.yeelight#7]
Hi. Is it possible to make different icons for different devices? I have a chandelier and two table lamps, and the icon is the same everywhere (chandelier). It looks pretty strange.

**Comment by jghaanstra** [comment]
Did you actually give my app 1 star in app store just because an icon is out of place it and I did not implement this feature within 2 days? If an incorrect icon is the only thing that is bugging you, do you really think an app deserves a 1 star rating? Next to that you should really learn to appreciate that app developers put in their free time creating these apps and do not ask anything in return (other than respect for their work and time put into it).

Could you give me the model identifiers of your Yeelights. You can find them in the official Yeelight app. Based on this model it should assign a corresponding icon. If it's showing the same icon everywhere it could be because a new model has been released that is not included in the app already.

**Comment by ElvisPresly** [comment]
I've already removed my review, and hastened to conclusions.

**Comment by ElvisPresly** [comment]
I also noticed that these lamps often come out into offline. Although they are connected to wi-fi network  
Thank you
![8B03BBBA-1602-4EF9-A61B-8FA4F29F2BAD](https://user-images.githubusercontent.com/18265958/93869084-08418780-fcd4-11ea-9ba9-e14b1166e375.jpeg)
![3C889205-4627-44E9-9DDB-3D8219882F42](https://user-images.githubusercontent.com/18265958/93869086-0972b480-fcd4-11ea-9ec6-d5d33176761d.jpeg)

**Comment by ElvisPresly** [comment]
Also the plugin me offers choose color glow, on these lamps only support change temperature. If possible, fix please

**Comment by jghaanstra** [comment]
Thanx for the donation, much appreciated and a much beter incentive than a 1 star rating ... ;-)

I have probably fixed the issue with the incorrect icon and the color picker for the desklamp. The new version of my app (1.1.4) is pending approval in the app store. Once released by Athom it requires you to re-pair these lights to fix the icon and set the correct capability for these lights.

About the connection issues. I doubt this is related to my app. You seem to be the first to report this out of +750 users. So I'm guessing it's somehow related to your network configuration. Please restart my app, wait until the device becomes unavailable in Homey, then send a crash report from the settings of my app and create a new issue here refering the crash log ID. That should give me more information on what is going on.

I'm closing this issue for now as the icon should be fixed. If something is still not right after you receive the 1.1.4 update and have re-paired the device just post here again.

**Comment by ElvisPresly** [comment]
Hi, I get the wrong icon and color control.
![Uploading 1303F09E-A8FC-47C5-9AAD-844CA2092B09.png…]()

**Comment by jghaanstra** [comment]
> Hi, I get the wrong icon and color control.
> ![0C20B851-38FA-4215-8CDD-008130E7E108](https://user-images.githubusercontent.com/18265958/93998110-cb8d9300-fd9c-11ea-877d-6750a7405e8b.png)

Did you re-pair the device?

**Comment by ElvisPresly** [comment]
@jghaanstra 
Unic code
e64aa147-f2ec-47bf-9604-99d00fc3accf

**Comment by ElvisPresly** [comment]
> > Hi, I get the wrong icon and color control.
> 
> Did you re-pair the device?

Yes, I even reinstalled the app

**Comment by jghaanstra** [comment]
Pfff ... do you know how to run a app from the command line? I need extra debug logging.

**Comment by ElvisPresly** [comment]
> Pfff ... do you know how to run a app from the command line? I need extra debug logging.

I can do it only if there is an instruction

**Comment by jghaanstra** [comment]
Instruction on how to run an app from the command line with the command `homey app run` can be found here: https://community.athom.com/t/how-to-cli-install-method/198

I have created a debug version here on Github which you will need to run, it can be found here: https://github.com/jghaanstra/com.yeelight/tree/debug

When you are running this version please re-pair one of the desklamps and copy and paste the information that will show up in the console when the light is discovered. This info show give me the exact model which I need to filter on to assign the correct icon and capabilities.

**Comment by ElvisPresly** [comment]
I read it, it's very difficult for me. Is there an alternative way to fix this?

**Comment by jghaanstra** [comment]
> I read it, it's very difficult for me. Is there an alternative way to fix this?
> 
> model | "lamp4"

Try installing this test version from the app store and re-pair a desklamp to see if this version fixes it.

https://homey.app/a/com.yeelight/test/

**Comment by ElvisPresly** [comment]
> > I read it, it's very difficult for me. Is there an alternative way to fix this?
> > model | "lamp4"
> 
> Try installing this test version from the app store and re-pair a desklamp to see if this version fixes it.
> 
> https://homey.app/a/com.yeelight/test/

its Work Thanks
![IMG_C43EF880785E-1](https://user-images.githubusercontent.com/18265958/94001510-42c52600-fda1-11ea-8f7a-619e97e0747d.jpeg)

**Comment by ElvisPresly** [comment]
I have another question, should the center circle change color?

**Comment by jghaanstra** [comment]
Good. I'll update the version in the app store.

> I have another question, should the center circle change color?

What center circle?

**Comment by ElvisPresly** [comment]
> Good. I'll update the version in the app store.
> 
> > I have another question, should the center circle change color?
> 
> What center circle?

https://youtu.be/pcpKEZWDVGE

**Comment by jghaanstra** [comment]
What kelvin range does your lamp support?

**Comment by ElvisPresly** [comment]
2600 - 5000K

**Comment by jghaanstra** [comment]
Are you sure about that? All specifications I can find say the desklights have a range of 2700k-6500K. Do you have a product link where I can view the details?

**Comment by ElvisPresly** [comment]
<img width="598" alt="Снимок экрана 2020-09-23 в 13 52 36" src="https://user-images.githubusercontent.com/18265958/94003580-15c64280-fda4-11ea-9ca8-045c9a7ec46a.png">

**Comment by ElvisPresly** [comment]
https://www.mi.com/global/mi-led-desk-lamp-1s/specs

I don’t know why it is now under the MI brand. It used to be Yeelight

**Comment by jghaanstra** [comment]
Reinstall the test version and try again.

https://homey.app/a/com.yeelight/test/

**Comment by ElvisPresly** [comment]
This app has unexpectedly stopped
![IMG_53A74C138285-1](https://user-images.githubusercontent.com/18265958/94006260-414b2c00-fda8-11ea-9bfb-c9a497b980c0.jpeg)

**Comment by jghaanstra** [comment]
Try again.

(you also need to re-pair the desklamps to get it to work)

**Comment by ElvisPresly** [comment]
https://youtu.be/xkB1ei8w81c

**Comment by jghaanstra** [comment]
I give up. I can probably only fix that if I have the actual light to test with.

**Comment by ElvisPresly** [comment]
When I press the circles, the lamp changes the color temperature. It's like a bug in the interface

**Comment by jghaanstra** [comment]
Unless you loan or donate a device or learn how to run the app from the command line there is not much I can do. I checked the code again and I'm not seeing anything that could cause this. Are you sure you re-paired the device on version 1.1.7?

If so, only option is to debug it from the command line. If you have more information feel free to add it to the ticket.
