### ISSUE TITLE
GU10 Yeelight color bulbs

### ISSUE THREAD

**Issue by feyazbek** [jghaanstra/com.yeelight#9]
Hello. I have bought 34 of these GU10 Yeelights bulbs. I was able to add them to the Yeelight app and they are working fine. However the I have tried adding them to the homey Yeelight app without success. Can you please assist? See image 
![35377F96-D88E-488E-8B2A-67485AC2F37F](https://user-images.githubusercontent.com/58607338/114915476-e4869000-9e23-11eb-90bc-8cef2c72e093.jpeg)

**Comment by jghaanstra** [comment]
Please use the support forum for support. Github is for bugs and feature requests. And please supply more info other than "tried but it did not work".
